export const GA_TRACKING_ID = 'UA-105611120-1';

export const MAP_COORDS_GALACTIC = 'GALACTIC';
export const MAP_COORDS_EQUATORIAL = 'EQUATORIAL';
export const STAR_SHAPE_SPHERE = 'SPHERE';

export const ERROR_MISSING_PARAM = 'ERROR_MISSING_PARAM';
export const ERROR_UNHANDLED_ACTION = 'ERROR_UNHANDLED_ACTION';
